---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:

  - name: ..... collect ONTAP Info

    netapp.ontap.na_ontap_info:

      hostname: "{{ netapp_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

      use_python_keys: true

      gather_subset: storage/volumes
      fields: '*'
      
    register: volinfo

  - debug:
      var: volinfo

  - set_fact:
      vol1name: "{{ volinfo.ontap_info.storage_volumes.records.0.name }}"

  - debug:
      var: vol1name
